site_name: CodeLingo Docs #- On Prem
pages:
    - Overview: index.md
    - Getting Started: getting-started.md
    # - Platform: platform.md
    - CLQL: clql.md
    - Lexicons: lexicons.md
    - Tenets: tenets.md
    - Bots: bots.md
    # todo: use cases should be organised by: query and bot. The cases below
    # should all be under query.
    - Use Cases: 
        - AST: use-cases/ast.md
        - VCS: use-cases/vcs.md
        - Runtime: use-cases/runtime.md
        - Integration: use-cases/integration.md
    # - Lexicon SDK: lexicon-sdk.md
    # - Bot SDK: bot-sdk.md
    
theme: cinder