site_name: CodeLingo Docs #- On Prem
pages:
    - Home: index.md
    - User Guide:
      - Getting Started: getting-started.md
      - Tenets: concepts/tenets.md
      - Flows and Bots: concepts/flows.md
      - Help & Support: help.md

theme: cinder